#!/usr/bin/env node
/**
 * Writes an example `DraftBrief` from the regression corpus.
 *
 *     npm run brief                          # middle pick of the newest mock
 *     npm run brief -- <draftId> <pickNo>    # a specific selection
 *
 * The brief is generated by the same code the live path will use, so it can
 * never document a shape the engine stopped producing. Handy for eyeballing
 * exactly what the strategist is being handed before wiring up a model.
 */
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const [draftId, pickNo] = process.argv.slice(2);
const out = resolve('data/regression/example-brief.json');

const result = spawnSync(
  'npx',
  [
    'vitest', 'run', '--config', 'vitest.config.ts',
    'tests/regression/strategist-brief.test.ts',
    '-t', 'reports what a real brief contains',
    '--reporter=verbose',
  ],
  {
    stdio: 'inherit',
    env: {
      ...process.env,
      JUANCHO_BRIEF_OUT: out,
      ...(draftId ? { JUANCHO_BRIEF_DRAFT: draftId } : {}),
      ...(pickNo ? { JUANCHO_BRIEF_PICK: pickNo } : {}),
    },
  },
);
process.exit(result.status ?? 1);
